
version: 2

updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 50
  assignees: 
    - "guibranco"
  reviewers: 
    - "guibranco"
  labels:
    - "github-actions"
    - "dependencies"
