version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "vitest",
    "browser"
  ]

[[transformers]]
name = "prettier"